platform: "onnxruntime_onnx"
max_batch_size: 1
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ 128 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ 128 ]
  },
  {
    name: "token_type_ids"
    data_type: TYPE_INT64
    dims: [ 128 ]
  }
]
output [
  {
    name: "last_hidden_state"
    data_type: TYPE_FP32
    dims: [ -1, 768 ]
  },
  {
    name: "1388"
    data_type: TYPE_FP32
    dims: [ 768 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
